#!/bin/bash

FILES=""
ARGS=""
for arg in "$@" ; do
  case "$arg" in
    -*)       ARGS+=" $arg";;
    source/*) FILES+=" ../../$arg";;
    *)        FILES+=" harnesses/${arg}.c";;
  esac
done

cprover --safety -I ../../include $ARGS $FILES
