#!/bin/bash

doit() {
  printf "** $*"
  LAST=${@: -1}

  start=`perl -MTime::HiRes=time -e 'printf "%.9f\n", time'`
  ./doit $* > logs/${LAST}.log 2>&1
  RESULT=$?
  end=`perl -MTime::HiRes=time -e 'printf "%.9f\n", time'`

  if [ $RESULT -eq 0 ] ; then
    printf ' \e[32mOK\e[0m'
  elif [ $RESULT -eq 10 ] ; then
    printf ' \e[31mREFUTED\e[0m'
  else
    printf ' \e[1;31mERROR\e[0m'
  fi

  runtime=$( echo "$end - $start" | bc -l )
  printf " %f" $runtime

  printf '\n'
}

skip() {
  printf "** $*"
  printf ' \e[37mSKIPPED\e[0m'
  printf '\n'
}

if [ ! -e logs/. ] ; then mkdir logs ; fi

# source/allocator.c
doit source/allocator.c aws_mem_acquire
skip source/allocator.c aws_mem_acquire_many VA_ARGS
skip source/allocator.c aws_mem_calloc SLOW
skip source/allocator.c aws_mem_realloc SLOW

# source/allocator_sba.c
skip source/allocator_sba.c source/allocator.c aws_small_block_allocator_bytes_active SIMPLIFIER
skip source/allocator_sba.c aws_small_block_allocator_bytes_reserved SLOW
skip source/allocator_sba.c aws_small_block_allocator_new SLOW

# source/bus.c
skip source/bus.c s_bus_destroy_listener_list LINKED_LIST

# source/byte_buf.c
doit source/byte_buf.c aws_array_eq_c_str
doit source/byte_buf.c aws_array_eq_c_str_ignore_case
doit source/byte_buf.c aws_array_eq_ignore_case
doit source/byte_buf.c aws_byte_buf_advance
skip source/byte_buf.c aws_byte_buf_append_with_lookup INVARIANT
skip source/byte_buf.c aws_byte_buf_cat VA_ARGS
doit source/byte_buf.c aws_byte_buf_init
skip source/byte_buf.c aws_byte_buf_init_cache_and_update_cursors VA_ARGS
doit source/byte_buf.c aws_byte_buf_init_copy
doit source/byte_buf.c aws_byte_buf_init_copy_from_cursor
doit source/byte_buf.c aws_byte_buf_reserve
doit source/byte_buf.c aws_byte_buf_reserve_relative
skip source/byte_buf.c aws_byte_cursor_compare_lookup INVARIANT
skip source/byte_buf.c aws_byte_cursor_find_exact SLOW
skip source/byte_buf.c aws_byte_cursor_left_trim_pred INVARIANT
skip source/byte_buf.c aws_byte_cursor_next_split HARNESS
skip source/byte_buf.c aws_byte_cursor_right_trim_pred INVARIANT
skip source/byte_buf.c aws_byte_cursor_split_on_char_n SLOW
doit source/byte_buf.c aws_hash_array_ignore_case

# source/cache.c

# source/codegen.c
skip source/codegen.c source/allocator.c aws_array_list_clean_up SIMPLIFIER
skip source/codegen.c source/allocator.c aws_array_list_clean_up_secure SIMPLIFIER
doit source/codegen.c aws_array_list_init_dynamic
doit source/codegen.c aws_is_mem_zeroed
doit source/codegen.c aws_linked_list_is_valid_deep
doit source/codegen.c aws_linked_list_node_reset
doit source/codegen.c aws_text_detect_encoding

# source/command_line_parser.c
skip source/command_line_parser.c source/byte_buf.c aws_cli_dispatch_on_subcommand QUANTIFIERS

# source/common.c

# source/condition_variable.c
doit source/condition_variable.c aws_condition_variable_wait_for_pred
doit source/condition_variable.c aws_condition_variable_wait_pred

# source/date_time.c
skip source/date_time.c aws_date_time_init_from_str SLOW
skip source/date_time.c aws_date_time_init_from_str_cursor SLOW
doit source/date_time.c s_get_time_struct

# source/device_random.c

# source/encoding.c
skip source/encoding.c aws_base64_decode SIMPLIFIER
skip source/encoding.c aws_base64_encode SLOW
skip source/encoding.c aws_hex_decode SLOW
skip source/encoding.c aws_hex_encode SLOW
skip source/encoding.c aws_hex_encode_append_dynamic SLOW

# source/error.c

# source/fifo_cache.c

# source/file.c
skip source/file.c source/allocator.c source/byte_buf.c aws_byte_buf_init_from_file SIMPLIFIER
skip source/file.c aws_directory_entry_iterator_destroy LINKED_LIST

# source/hash_table.c
skip source/hash_table.c aws_hash_byte_cursor_ptr SLOW
doit source/hash_table.c aws_hash_callback_c_str_eq
doit source/hash_table.c aws_hash_callback_string_eq
skip source/hash_table.c aws_hash_iter_begin LINKED_LIST
skip source/hash_table.c aws_hash_string SLOW
skip source/hash_table.c aws_hash_table_clear LINKED_LIST
skip source/hash_table.c aws_hash_table_eq LINKED_LIST
skip source/hash_table.c aws_hash_table_find LINKED_LIST
skip source/hash_table.c aws_hash_table_foreach LINKED_LIST
skip source/hash_table.c aws_hash_table_init SLOW
skip source/hash_table.c aws_hash_table_move LINKED_LIST
skip source/hash_table.c aws_hash_table_remove LINKED_LIST
skip source/hash_table.c aws_hash_table_remove_element LINKED_LIST

# source/json.c

# source/lifo_cache.c

# source/linked_hash_table.c
skip source/linked_hash_table.c source/hash_table.c aws_linked_hash_table_clean_up LINKED_LIST

# source/log_channel.c

# source/log_formatter.c

# source/log_writer.c

# source/logging.c
doit source/logging.c aws_log_level_to_string
doit source/logging.c aws_string_to_log_level
doit source/logging.c aws_thread_id_t_to_string

# source/lru_cache.c

# source/math.c
skip source/math.c aws_add_size_checked_varargs VA_ARGS

# source/memtrace.c
skip source/memtrace.c aws_mem_tracer_dump SLOW
skip source/memtrace.c aws_mem_tracer_new VA_ARGS

# source/priority_queue.c
skip source/priority_queue.c aws_priority_queue_backpointers_valid_deep HARNESS
skip source/priority_queue.c aws_priority_queue_init_dynamic SLOW
doit source/priority_queue.c aws_priority_queue_init_static
skip source/priority_queue.c aws_priority_queue_pop LINKED_LIST
skip source/priority_queue.c aws_priority_queue_remove LINKED_LIST
doit source/priority_queue.c aws_priority_queue_top

# source/process_common.c
doit source/process_common.c aws_run_command
doit source/process_common.c source/allocator.c aws_run_command_result_init

# source/promise.c

# source/ref_count.c

# source/ring_buffer.c
skip source/ring_buffer.c aws_ring_buffer_acquire SLOW
skip source/ring_buffer.c aws_ring_buffer_clean_up SLOW
skip source/ring_buffer.c aws_ring_buffer_init PROPERTYBUG
skip source/ring_buffer.c aws_ring_buffer_release SLOW

# source/statistics.c

# source/string.c
doit source/string.c aws_secure_strlen
doit source/string.c source/allocator.c aws_string_new_from_array

# source/task_scheduler.c
doit source/task_scheduler.c aws_task_init
skip source/task_scheduler.c source/priority_queue.c aws_task_scheduler_clean_up SLOW
doit source/task_scheduler.c aws_task_scheduler_init
skip source/task_scheduler.c aws_task_scheduler_schedule_future SIMPLIFIER

# source/thread_scheduler.c
skip source/thread_scheduler.c aws_thread_scheduler_cancel_task LINKED_LIST

# source/thread_shared.c
skip source/thread_shared.c aws_thread_join_all_managed LINKED_LIST

# source/uuid.c
skip source/uuid.c aws_uuid_init_from_str SSCANF
doit source/uuid.c aws_uuid_to_str

# source/xml_parser.c
skip source/xml_parser.c aws_xml_node_traverse SLOW
skip source/xml_parser.c aws_xml_parser_parse SLOW
skip source/xml_parser.c s_advance_to_closing_tag LINKED_LIST
skip source/xml_parser.c s_node_next_sibling SLOW
